(function () {
  'use strict';

  if (!window.translations) return;

  const path = window.location.pathname || '';
  const isTerms = /terms\.html?$|\/terms\/?$/.test(path) || path.toLowerCase().includes('terms');
  const isPrivacy = /privacy\.html?$|\/privacy\/?$/.test(path) || path.toLowerCase().includes('privacy');
  if (!isTerms && !isPrivacy) return;

  const prefix = isTerms ? 'terms' : 'privacy';

  const enStrings = {
    terms: {
      page_title: 'Terms of Service | NexusV',
      heading: 'Terms of Service',
      category: 'Legal',
      effective: 'Last updated: July 20, 2026 · Effective: July 20, 2026',
      meta_description: 'NexusV Terms of Service, defining the rights and obligations of both parties, service scope, acceptable use, intellectual property, disclaimers, indemnification and dispute resolution.',
      content: `
            <div class="legal-toc" aria-label="Table of contents">
                <p class="legal-toc-title">Table of Contents</p>
                <ol>
                    <li><a href="#s1">Acceptance of Terms</a></li>
                    <li><a href="#s2">Service Description</a></li>
                    <li><a href="#s3">Account and Login</a></li>
                    <li><a href="#s4">Acceptable Use</a></li>
                    <li><a href="#s5">User Representations and Warranties</a></li>
                    <li><a href="#s6">Content and Intellectual Property</a></li>
                    <li><a href="#s7">API Use</a></li>
                    <li><a href="#s8">Payment, Subscription and Refund</a></li>
                    <li><a href="#s9">Service Changes, Suspension and Termination</a></li>
                    <li><a href="#s10">Logs and Records</a></li>
                    <li><a href="#s11">Disclaimers and Limitation of Liability</a></li>
                    <li><a href="#s12">Indemnification</a></li>
                    <li><a href="#s13">Governing Law and Dispute Resolution</a></li>
                    <li><a href="#s14">Amendments to the Terms</a></li>
                    <li><a href="#s15">Operator and Contact Us</a></li>
                </ol>
            </div>

            <h2 id="s1">1. Acceptance of Terms</h2>
            <p>Welcome to NexusV (hereinafter “the Service”). These Terms of Service (hereinafter “the Terms”) constitute a legally binding agreement between you and the operator of the Service (hereinafter “we” or “the Operator”). By registering for, logging into, or otherwise using the Service, you represent that you have read, understood, and agreed to be bound by all provisions of these Terms. If you do not agree to any part of these Terms, please stop using the Service immediately.</p>
            <p><strong>Special Notice:</strong> Content in these Terms that is presented in bold, underlined, or otherwise reasonably brought to your attention may include provisions that limit or exclude the liability of the Operator, impose additional obligations on you, or restrict your rights. Please read them carefully before registering, logging in, or making any payment, and use the Service only after fully understanding them.</p>

            <h2 id="s2">2. Service Description</h2>
            <p>NexusV is a technical access and dialogue platform that aggregates third-party artificial intelligence models, providing you with web-based chat, the Cancri Code desktop client, and an Open API. <strong>The Service only provides model-call aggregation, request forwarding, account management, billing and technical support. It does not participate in model training, does not manually review model outputs, and is not the creator or publisher of any model output.</strong></p>
            <p>To complete request forwarding and ensure service quality, we may perform necessary format conversion, protocol adaptation, routing selection, caching, security inspection, rate control, content filtering and error handling on your requests; however, the final model output is generated by the third-party model service provider you select.</p>
            <p>The Service is provided “as is.” While we make reasonable efforts to ensure stability and availability, we make no express or implied warranties regarding the availability, output quality, content accuracy, policy changes or technical interruptions of third-party model service providers. The Service is operated by an independent entity with existing technology and resources and does not commit to any service-level agreement (SLA) or specific response time.</p>
            <p>The Service is available to users worldwide. If the Service is prohibited in your jurisdiction, or if you are a sanctioned country, region, entity or individual, please do not register or use the Service.</p>

            <h2 id="s3">3. Account and Login</h2>
            <h3>3.1 Registration Method</h3>
            <p>The Service uses email one-time password (OTP) login; no account password is set. You must provide a real, valid email address that can receive messages, and complete login after receiving the verification code.</p>

            <h3>3.2 Account Responsibility</h3>
            <p>You should keep the email address and verification code used for login secure and are fully responsible for all operations performed through your account. If you discover any unauthorized use of your account, please notify us immediately through the contact information at the end of these Terms.</p>

            <h3>3.3 One Account Per Person</h3>
            <p>Each natural person may in principle register only one account. You may not register accounts in bulk, or sell, rent, lend, transfer or share accounts. If any violation of the above is discovered, we have the right to freeze or cancel the relevant accounts immediately and reserve the right to pursue legal liability.</p>

            <h3>3.4 Age Restriction</h3>
            <p>The Service is not directed to children under 14 years of age. If you are under 14, please do not register an account. If you discover that a child under 14 is using the Service, please contact us immediately; we will terminate the relevant account and handle the data in accordance with the <a href="privacy.html">Privacy Policy</a> after verification.</p>

            <h2 id="s4">4. Acceptable Use</h2>
            <p>When using the Service, you may not engage in any of the following conduct:</p>
            <ol>
                <li>Violate the laws and regulations of the People’s Republic of China, or the laws and regulations of your jurisdiction;</li>
                <li>Use the Service for activities that violate export controls, economic sanctions, anti-money laundering, counter-terrorism financing or other laws and regulations, or provide services to sanctioned countries, regions, entities or individuals;</li>
                <li>Generate, transmit or store illegal or harmful content involving terrorism, violence, pornography, gambling, drugs, cults, ethnic hatred, disinformation, etc.;</li>
                <li>Infringe the copyrights, trademark rights, patent rights, portrait rights, privacy rights, trade secrets or other lawful rights and interests of others;</li>
                <li>Use automated scripts, crawlers, robots or unofficial clients to access the Service;</li>
                <li>Circumvent, bypass, interfere with or disrupt the Service’s access control, quota limits, verification codes, rate limits or security mechanisms;</li>
                <li>Carry out denial-of-service attacks, injection attacks, vulnerability probing, reverse engineering, decompilation, disassembly or other destructive acts against the Service;</li>
                <li>Register or use an account by deception, forgery or impersonation of another person;</li>
                <li>Use the Service’s free quota, subscription benefits or API resources for unauthorized commercial resale, secondary sales, large-scale distribution or provision of paid services to third parties;</li>
                <li>Engage in any conduct that may harm the Service, other users or third parties’ lawful rights and interests.</li>
            </ol>
            <p>For conduct that violates the above norms, we have the right to take measures including but not limited to warnings, throttling, downgrading, freezing accounts, terminating services, revoking API keys and pursuing legal liability, without prior notice.</p>

            <h2 id="s5">5. User Representations and Warranties</h2>
            <p>When using the Service, you represent and warrant that:</p>
            <ol>
                <li>You have full civil capacity, or have obtained the consent of your guardian or legal representative;</li>
                <li>You own lawful rights to, or have obtained necessary authorization for, any content you submit, upload or input;</li>
                <li>Your submitted content does not infringe any third-party intellectual property rights, portrait rights, privacy rights, trade secrets or other lawful rights and interests;</li>
                <li>Your use does not violate any applicable laws, regulations, rules, policies or industry standards;</li>
                <li>When using the API or third-party model services, you will comply with the use policies, API terms, rate limits and acceptable use policies of the corresponding upstream model service providers;</li>
                <li>You will not use model outputs directly for medical diagnosis, legal opinions, financial investment, tax planning, psychological counseling or other professional decisions without independent verification;</li>
                <li>You will not use the Service for illegal, fraudulent, harassing, defamatory, hateful, discriminatory, violent, terrorist, gambling, money-laundering, tax-evasion or regulatory-evasion purposes.</li>
            </ol>

            <h2 id="s6">6. Content and Intellectual Property</h2>
            <h3>6.1 Your Input</h3>
            <p>Text, images, files and other content that you input or upload through the Service are and remain owned by you or the original rights holder. You should ensure that your input is lawful and does not infringe third-party rights. In order to provide the Service, you authorize us and the third-party model service provider you select to process your input within the necessary scope, in accordance with the rules set out in the <a href="privacy.html">Privacy Policy</a>.</p>

            <h3>6.2 Model Output</h3>
            <p>The ownership of output generated by each model service provider is determined by that provider’s terms of service. The Service does not claim ownership of any model output, acts only as a technical access platform, and does not assume the principal responsibility for generating the output. The Service may perform necessary format conversion, routing, caching, security inspection and filtering on requests, but is not responsible for the final content generated by the model. When using, copying or distributing outputs, you should comply with the corresponding upstream terms of service.</p>

            <h3>6.3 Platform Intellectual Property</h3>
            <p>Except for your input and model outputs, the copyrights and other intellectual property rights in the Service’s website design, source code, interface, brand identity, domain names and documentation belong to the Operator. Without our written authorization, you may not copy, modify, distribute or commercially exploit the above content.</p>

            <h2 id="s7">7. API Use</h2>
            <p>The Service provides developers with an API compatible with common protocols such as OpenAI and Anthropic, but you understand and agree that:</p>
            <ol>
                <li>We do not guarantee that any model will remain continuously available or online; the model list, model names, parameters, billing standards and multipliers may be adjusted at any time;</li>
                <li>Upstream model service providers may take models offline, impose rate limits, change policies or adjust prices at any time, causing calls to fail, time out, return errors or be rejected;</li>
                <li>The API compatibility provided by us is as described in the <a href="chat/api_docs_detail.html#intro">API Documentation</a>; we do not guarantee it is 100% consistent with the latest upstream version;</li>
                <li>Retry, timeout and retry strategies do not guarantee that every call will succeed;</li>
                <li>API Keys (prefixed with <code>cancri_sk_</code>) are for your personal or organizational use only, and may not be shared, rented, sold, embedded in public repositories or clients;</li>
                <li>There is an upper limit on the number of active API Keys each account may hold at the same time, as displayed in the <a href="chat/api_keys.html">API Key console</a>;</li>
                <li>Pay-as-you-go API top-ups are credited to an independent wallet, completely isolated from Chat/IDE plan quotas.</li>
            </ol>

            <h2 id="s8">8. Payment, Subscription and Refund</h2>
            <h3>8.1 Billing Method</h3>
            <p>The Service offers a Free tier, monthly subscription tiers (Go / Plus / Pro), one-time top-up packages (if available), and pay-as-you-go API top-ups for developers. Specific tiers, prices, quotas, model multipliers, overflow rules and error codes are as displayed on the <a href="chat/pricing.html">purchase page</a>, the <a href="chat/api_models.html">model gallery</a> and the <a href="chat/api_docs_detail.html#intro">API documentation</a> at the relevant time.</p>
            <p>The Chat/IDE monthly quota pool and the API wallet are independent and not interchangeable. Monthly subscription quotas reset each billing cycle; unused portions generally do not carry over to the next cycle; monthly subscriptions do not auto-renew and must be manually repurchased after expiry; after the plan quota is exhausted, pay-as-you-go overflow may apply, with specific overflow discounts and rules as displayed on the purchase page.</p>

            <h3>8.2 Payment and Activation</h3>
            <p>You may select a tier or top-up package on the purchase page and pay by scanning the WeChat Pay or Alipay QR code. Please enter in the remarks or message an email address and QQ or WeChat ID consistent with your account, so that the Operator can reconcile the payment. After manual verification, the Operator will generate an activation code on the order page. You must enter the activation code yourself to complete the upgrade or credit the top-up. The Service does not integrate any third-party payment-platform SDK and does not touch your payment credentials.</p>

            <h3>8.3 Refund</h3>
            <p><strong>Except as otherwise provided by law or these Terms, activated plans or top-up packages are non-refundable.</strong> The amount you paid is mainly used to cover upstream model API costs. Refunds may be requested in the following circumstances: (1) after payment, no order was submitted or no activation code was claimed; (2) due to a major failure of the Service during the paid period, the Service was unusable and the failure, as confirmed by the Operator’s system logs or third-party monitoring tools, lasted for more than 50% of the effective period of the order. Refund requests should be sent to the email address at the end of these Terms.</p>

            <h2 id="s9">9. Service Changes, Suspension and Termination</h2>
            <p>We reserve the right to decide, at our sole discretion, whether to accept a registration, continue providing services to a specific user, open or restrict a particular model, or restrict access from a particular region or class of IP addresses. We also reserve the following rights without liability to you:</p>
            <ul>
                <li>To add, modify, suspend or terminate any function of the Service at any time according to business needs;</li>
                <li>To adjust the available model list, billing method or interface protocol according to changes in third-party model service provider policies;</li>
                <li>To freeze, restrict or cancel accounts that violate laws, regulations, security audits or anti-abuse requirements;</li>
                <li>To suspend the Service due to force majeure, upstream failures, network interruptions, government actions, cyber attacks, computer viruses, power failures, equipment failures, communication line interruptions or other reasons beyond our reasonable control.</li>
            </ul>
            <p>To ensure service security and prevent abuse, we have the right to investigate abnormal calls, large-scale token consumption, proxy resale, robot behavior and suspected illegal or harmful content, and to request that you provide additional identity information. If necessary, we may suspend, restrict or terminate services, freeze or cancel accounts, or revoke API keys without prior notice.</p>

            <h2 id="s10">10. Logs and Records</h2>
            <p>To ensure service security, prevent abuse, comply with legal obligations and handle disputes, we may retain necessary logs and records, including: request time, request ID, user ID, model name, endpoint called, input/output token counts, billing amount, IP address, User-Agent, device identification information, error logs, payment reconciliation records, and account suspension/violation handling records. The retention, use and deletion of such logs are governed by the <a href="privacy.html">Privacy Policy</a> and applicable laws and regulations. You acknowledge that such records may serve as the basis for us to handle abuse, disputes or compliance matters.</p>

            <h2 id="s11">11. Disclaimers and Limitation of Liability</h2>
            <h3>11.1 Service Use Notice</h3>
            <p>You understand and agree that artificial intelligence model outputs may contain: factual errors, omissions, outdated content, bias, statements inconsistent with facts, fabricated references or sources, content that infringes third-party rights, and content that does not comply with local laws and regulations. The outputs do not constitute professional advice such as medical, legal, financial, tax or psychological counseling. You should independently verify the reliability of outputs and bear the risks arising from any decisions made based on them.</p>

            <h3>11.2 Limitation of Liability</h3>
            <p><strong>To the maximum extent permitted by applicable law, we are not liable for any direct, indirect, incidental, special, punitive or consequential damages arising from your use or inability to use the Service, or reliance on outputs, including but not limited to lost profits, data loss, loss of goodwill, business interruption, or the cost of substitute services.</strong></p>
            <p><strong>We are not liable for our inability to perform the Service due to force majeure, upstream service interruption, changes in third-party model service provider policies, network regulation, government actions, cyber attacks, computer viruses, power failures, equipment failures, communication line interruptions or other reasons beyond our reasonable control.</strong></p>
            <p><strong>This section does not apply to personal injury or property loss caused by our intentional misconduct or gross negligence.</strong></p>

            <h2 id="s12">12. Indemnification</h2>
            <p>If your violation of these Terms, applicable laws and regulations, third-party terms of service, or infringement of any third-party lawful rights and interests causes the Operator, its affiliates, employees, agents or partners to suffer any claims, penalties, investigations, litigation, arbitration, attorneys’ fees, investigation costs or other losses, you shall bear full liability for compensation and hold the Operator harmless.</p>
            <p>If your violation causes the Operator to be subject to any claim, penalty or demand by a third party (including but not limited to regulatory authorities, copyright holders or upstream model service providers), you agree to actively cooperate with the investigation and bear all reasonable costs incurred by the Operator as a result.</p>

            <h2 id="s13">13. Governing Law and Dispute Resolution</h2>
            <p>The conclusion, effectiveness, interpretation, performance and dispute resolution of these Terms shall be governed by the laws and regulations of mainland China (excluding the laws of the Hong Kong Special Administrative Region, the Macao Special Administrative Region and the Taiwan region).</p>
            <p>Any dispute arising from or in connection with these Terms shall first be resolved through friendly negotiation between the parties; if negotiation fails, either party may file a lawsuit with the competent people’s court at the Operator’s principal place of business or registered domicile. The parties may also separately agree to submit the dispute to a mutually selected arbitration institution for arbitration in accordance with its then-effective arbitration rules.</p>
            <p>If any provision of these Terms is held to be invalid, unlawful or unenforceable, that provision shall be modified or excluded to the minimum extent necessary, and the remaining provisions shall remain effective and binding on both parties (severability).</p>

            <h2 id="s14">14. Amendments to the Terms</h2>
            <p>We may revise these Terms from time to time. The revised Terms will be published on this page and marked with the “Last updated” date. For revisions that affect your material rights and interests, we will inform you 7 days in advance through site announcements, in-site notices or registered email. By continuing to use the Service after the revised Terms take effect, you are deemed to accept the revised Terms. If you do not agree to the revision, please stop using the Service.</p>

            <h2 id="s15">15. Operator and Contact Us</h2>
            <p>The Service is provided by an independent operator. If you need to know the operator’s specific information, qualifications or contact details, please contact us through the following methods:</p>
            <ul>
                <li><strong>Email</strong>: <a href="mailto:nexusvai@139.com">nexusvai@139.com</a> / <a href="mailto:nexusvai@foxmail.com">nexusvai@foxmail.com</a></li>
                <li><strong>GitHub Issues</strong>: <a href="https://github.com/NexusVAI" target="_blank" rel="noopener">github.com/NexusVAI</a></li>
                <li><strong>X (Twitter)</strong>: <a href="https://x.com/NexusVAI" target="_blank" rel="noopener">@NexusVAI</a></li>
                <li><strong>Website</strong>: <a href="https://www.nexusvai.xyz/" target="_blank" rel="noopener">www.nexusvai.xyz</a></li>
            </ul>
            <p>Please do not send API Keys, verification codes, ID numbers or other sensitive information by email or Issue. We will confirm receipt within a reasonable time and respond as soon as possible.</p>

            <p class="legal-footer-note">
                <strong>The Chinese version of these Terms is the authoritative version; if there are other language translations and they conflict with the Chinese version, the Chinese version shall prevail.</strong>
            </p>
      `.trim()
    },
    privacy: {
      page_title: 'Privacy Policy | NexusV',
      heading: 'Privacy Policy',
      category: 'Legal',
      effective: 'Last updated: July 20, 2026 · Effective: July 20, 2026',
      meta_description: 'NexusV Privacy Policy, explaining how we collect, use, share, transfer internationally and protect your personal information, and stating your rights and choices.',
      content: `
            <p class="legal-summary"><strong>Important Notice:</strong> When you use chat, generation, API and other functions, the Service will forward your input to the third-party model service provider you select; that provider may be located outside mainland China. To provide the Service, we need to process and transfer part of your information internationally. Please make sure you understand this Policy before using the Service.</p>

            <div class="legal-toc" aria-label="Table of contents">
                <p class="legal-toc-title">Table of Contents</p>
                <ol>
                    <li><a href="#p1">Scope of Application</a></li>
                    <li><a href="#p2">Definitions</a></li>
                    <li><a href="#p3">Information We Collect</a></li>
                    <li><a href="#p4">How We Use Information and Legal Bases</a></li>
                    <li><a href="#p5">Processing and Sharing</a></li>
                    <li><a href="#p6">Data Storage and Security</a></li>
                    <li><a href="#p7">Cookies and Local Storage</a></li>
                    <li><a href="#p8">Cross-border Data Transfers</a></li>
                    <li><a href="#p9">Protection of Minors</a></li>
                    <li><a href="#p10">Your Rights</a></li>
                    <li><a href="#p11">Policy Updates</a></li>
                    <li><a href="#p12">Operator and Contact Us</a></li>
                </ol>
            </div>

            <h2 id="p1">1. Scope of Application</h2>
            <p>This Privacy Policy (hereinafter “this Policy”) applies to all products and services provided to you by NexusV (hereinafter “the Service” or “we”) through the website, desktop client, Open API and related functions. This Policy and the <a href="terms.html">Terms of Service</a> together form the basic rules governing your use of the Service. By using the Service, you represent that you have read, understood and agreed to this Policy.</p>

            <h2 id="p2">2. Definitions</h2>
            <p>The meanings of relevant terms in this Policy are as follows:</p>
            <ul>
                <li><strong>Personal information</strong>: information relating to an identified or identifiable natural person recorded in electronic or other form, excluding information after anonymization.</li>
                <li><strong>Sensitive personal information</strong>: personal information that, once disclosed or used unlawfully, is likely to harm the dignity of a natural person or endanger personal or property safety, including biometric, religious belief, specific identity, medical health, financial account, and行踪轨迹 (location trail) information.</li>
                <li><strong>Processing</strong>: includes the collection, storage, use, processing, transmission, provision, disclosure and deletion of personal information.</li>
                <li><strong>Personal information controller</strong>: an organization or individual that independently decides the purposes and means of processing.</li>
                <li><strong>Processor</strong>: an organization or individual that processes personal information on behalf of and under the instructions of a controller.</li>
                <li><strong>Third-party service provider</strong>: an independent third party that provides us with model capability, cloud computing, database, email communication, human-machine verification and other services.</li>
                <li><strong>Model service provider</strong>: an upstream third party that provides underlying large language models or multimodal generation capabilities.</li>
            </ul>

            <h2 id="p3">3. Information We Collect</h2>
            <p>We collect personal information only to the extent necessary to provide services to you.</p>

            <h3>3.1 Information You Provide Voluntarily</h3>
            <ul>
                <li><strong>Account information</strong>: email address. The Service uses email one-time password (OTP) for registration and login; no account password is set.</li>
                <li><strong>Payment reconciliation information</strong>: if you purchase a subscription or top-up package, you need to submit an email address and QQ or WeChat ID consistent with the payment remarks on the purchase page, so the Operator can reconcile the payment manually and issue an activation code.</li>
                <li><strong>Conversation and generated content</strong>: text, images, files, prompts, and the model, parameters and settings you select when using chat, image generation, video generation, file analysis and other functions.</li>
                <li><strong>Feedback and appeal information</strong>: bug reports, feature suggestions, appeal materials and user evaluations you actively submit.</li>
                <li><strong>Model improvement authorization</strong>: you may choose in Settings whether to allow your conversation data to be used to improve the Cancri model. This function is turned on by default; it is processing for a purpose beyond the basic service and is based on your consent, and you may turn it off at any time in Settings. After turning it off, new conversations will still be saved for your review but will be marked as not participating in model training. Before turning it off, please do not input other people’s personal information or content subject to confidentiality obligations.</li>
            </ul>

            <h3>3.2 Information We Collect Automatically</h3>
            <ul>
                <li><strong>Device and network information</strong>: IP address, User-Agent, browser type, operating system, screen resolution, time zone and language preference.</li>
                <li><strong>Usage records and server logs</strong>: for each request, the model identifier, call time, request ID, input/output token count, billing amount (if applicable), session metadata, interface response status, IP address, User-Agent and error logs.</li>
                <li><strong>Client diagnostic information</strong>: with your explicit consent, when an uncaught JavaScript exception occurs we collect browser UA, current page URL, viewport size, exception message and stack, the URLs and status codes of the most recent 10 fetch requests (excluding request or response bodies), and a locally generated anonymous identifier, to locate and fix client-side issues. If you do not consent, we will not collect the above information.</li>
                <li><strong>Device identification information</strong>: after you log in, in order to detect multi-account abuse on the same device and to maintain network and account security, we may collect browser Canvas, WebGL, Audio fingerprint, WebRTC IP, fonts, screen, time zone, navigator information, hardware concurrency, device memory and other metrics in accordance with the provisions of the Cybersecurity Law and the Personal Information Protection Law concerning network security and personal information protection obligations, and generate an irreversible device identifier. This information is used only for anti-fraud and account security, not for advertising, profiling or personalized recommendations, and is not reported to third parties. The same browser usually reports once every 24 hours, silently on failure, without affecting normal use. Because of security and risk-control requirements, this function usually cannot be turned off; if you do not agree, please stop using the Service.</li>
                <li><strong>Human-machine verification information</strong>: during login and registration, we may require you to complete human-machine verification provided by Cloudflare Turnstile. Turnstile only returns the verification result and is not used for cross-site advertising tracking.</li>
            </ul>

            <h3>3.3 Information We Do Not Collect</h3>
            <p>We do not actively collect the following information: precise geolocation, address book, photo album, microphone, camera, biometric information, ID number, bank card number or payment password. The Service does not integrate any third-party payment-platform SDK; payment is made by you directly by scanning a WeChat Pay or Alipay QR code, and we do not touch your payment credentials.</p>

            <h3>3.4 Separate Consent</h3>
            <p>In accordance with the separate-consent requirements of the Personal Information Protection Law, the following processing activities require you to give separate consent on the basis of full knowledge. By reading this Policy and clicking “Agree,” you are deemed to have given separate consent to the following matters:</p>
            <ol>
                <li><strong>Providing information to model service providers</strong>: to complete chat or generation services, your input, prompts, files and context will be forwarded in real time to the third-party model service provider you select;</li>
                <li><strong>Cross-border transfer of personal information</strong>: the above information will be transferred outside mainland China (including to the jurisdiction where the model service provider and infrastructure service providers such as Cloudflare and Aiven are located) for processing;</li>
                <li><strong>Device identification information</strong>: after you log in, device identification information is collected and processed for account security and anti-fraud purposes;</li>
                <li><strong>Model improvement</strong>: after the “Model Improvement Authorization” is turned on in Settings, your conversation data will be used to improve the Cancri model; if you keep the default-on state, you are deemed to consent to such processing;</li>
                <li><strong>Client diagnostics</strong>: after explicit consent in the “Telemetry Consent” pop-up or Settings, client diagnostic information is collected.</li>
            </ol>
            <p>If you do not agree to any of the above, please do not use the corresponding function or the Service, and exercise your deletion right in accordance with Section 10.</p>

            <h2 id="p4">4. How We Use Information and Legal Bases</h2>
            <p>We process your personal information only for the following purposes:</p>
            <ol>
                <li>Completing account registration, login, identity verification and account security protection;</li>
                <li>Providing core services such as chat, text generation, image generation, video generation, file analysis and the Open API to you, and forwarding your input to the model service provider you select;</li>
                <li>Executing billing, quota management and usage statistics for plans, top-up packages and API wallets;</li>
                <li>Detecting abnormal login, volume brushing, automated abuse and cyber attacks, and performing necessary security scanning and content filtering in accordance with laws and regulations to protect the security of the Service and all users;</li>
                <li>Carrying out de-identified, aggregated service statistics, model effect analysis and product improvement;</li>
                <li>Using conversation data to improve the Cancri model within the scope of your authorization; if you turn off the authorization, new conversations will still be saved but marked as not participating in training;</li>
                <li>Handling your orders, appeals, customer-service requests and operational notices;</li>
                <li>Complying with laws, regulations and regulatory requirements, or cooperating with lawful investigations.</li>
            </ol>

            <h3>4.1 Legal Bases for Processing</h3>
            <p>We process personal information mainly on the following legal bases:</p>
            <ul>
                <li><strong>Obtaining individual consent</strong>: cross-border transfer, model improvement, client diagnostics, marketing communications (if any);</li>
                <li><strong>Necessary for performing a contract</strong>: account registration and login, providing chat/generation/API services, billing and quota management;</li>
                <li><strong>Necessary for fulfilling statutory duties or obligations</strong>: network security protection, security prevention, anti-fraud, content security management, cooperation with law enforcement and regulatory investigations, log retention;</li>
                <li><strong>Necessary for responding to public-health emergencies, or protecting natural persons’ life, health or property safety in emergencies</strong>: necessary processing in extreme emergency situations.</li>
            </ul>

            <h2 id="p5">5. Processing and Sharing</h2>
            <h3>5.1 Model Service Providers</h3>
            <p>To provide chat or generation services, your input (text, images, files, prompts, etc.) will be forwarded in real time to the model service provider you select. Such providers have their own independent privacy policies and terms of service, and act as independent personal information controllers for the data they receive; the Service only acts as a transmission channel, forwarding data between you and that provider, and does not control its subsequent processing. We are not directly responsible for their processing behavior.</p>
            <p>Depending on the model you select, overseas recipients may include but are not limited to OpenAI, Anthropic, Google, xAI, DeepSeek, Moonshot, Zhipu, Alibaba (Qwen), ByteDance (Doubao), Baidu, Tencent, MiniMax, Mistral and other entities; models deployed domestically or in cooperation may also be provided by the Service itself or by partners. The specific model, corresponding brand and provider are as displayed in real time in the <a href="chat/api_models.html">model gallery</a>, and are subject to the privacy policy published there.</p>

            <h3>5.2 Infrastructure and Communication Service Providers</h3>
            <p>We may entrust the following categories of third parties to process part of your information:</p>
            <ul>
                <li><strong>Cloud computing and edge-network service providers</strong> (such as Cloudflare): used to host gateways, stream responses, edge computing and security protection;</li>
                <li><strong>Managed database service providers</strong> (such as Aiven): used to store account, session, billing and usage-record data;</li>
                <li><strong>Email service providers</strong> (such as Resend): used to send verification codes, notices and operational emails to you;</li>
                <li><strong>Human-machine verification service providers</strong> (such as Cloudflare Turnstile): used for security verification during login.</li>
            </ul>
            <p>The above third parties are processors that handle data only in accordance with our instructions and contractual provisions, and may not use it beyond the agreed purposes.</p>

            <h3>5.3 Other Disclosures</h3>
            <p>Except as described above, we disclose your personal information only in the following circumstances:</p>
            <ul>
                <li>To comply with applicable laws, regulations, court orders or administrative supervision requirements, or to assist investigations conducted by state organs in accordance with law;</li>
                <li>When necessary to protect the life, property safety or other lawful rights and interests of the Service, users or third parties;</li>
                <li>In the event of a merger, acquisition, asset restructuring or similar transaction, where the transferee undertakes personal information protection obligations no lower than those set out in this Policy.</li>
            </ul>
            <p>Except as described above, we will not sell, rent or otherwise provide your personal information to any third party; in particular, we will not sell your chat history or personal information for advertising or marketing purposes.</p>

            <h2 id="p6">6. Data Storage and Security</h2>
            <h3>6.1 Storage Location and Retention Period</h3>
            <ul>
                <li><strong>Account information</strong>: retained until you cancel your account, after which it is deleted or anonymized within the period required by laws and regulations;</li>
                <li><strong>Conversation history</strong>: stored in a PostgreSQL database; you may delete individual sessions in the session list; after you delete a session, we will delete it from the active database as soon as possible, and if it cannot be deleted immediately due to backups, audits or legal requirements, we will delete or anonymize it within the shortest reasonable period necessary to achieve the deletion purpose; after account cancellation, it is deleted in accordance with the process;</li>
                <li><strong>Usage and billing records</strong>: retained for no less than the minimum period required by applicable laws and regulations;</li>
                <li><strong>Server logs</strong>: retained for a reasonable period for security audits, anti-abuse and dispute handling, after which they are rolled off or anonymized;</li>
                <li><strong>Client diagnostic logs</strong>: rolled off after problem location and repair, and not retained long-term;</li>
                <li><strong>Device identification information</strong>: retained for the period necessary to achieve account security and anti-fraud purposes, and disassociated after account cancellation;</li>
                <li><strong>Backup data</strong>: phased out in accordance with the rolling-backup policy of the managed database service provider.</li>
            </ul>

            <h3>6.2 Security Measures</h3>
            <p>We adopt industry-standard security measures to protect your information, including encrypted communication, identity authentication, access control, rate limiting and anomaly detection. Specific technical means may evolve with the security landscape, for example HTTPS/TLS, JSON Web Tokens, verification codes and least-privilege access. There is no absolute security on the Internet. If a data-security incident occurs, we will notify affected users through site announcements or registered email promptly after confirming the impact, and take reasonable measures to reduce the impact.</p>

            <h2 id="p7">7. Cookies and Local Storage</h2>
            <p>The Service uses the browser’s localStorage and sessionStorage to save the following categories of information:</p>
            <ul>
                <li><strong>Login state</strong>: access / refresh token;</li>
                <li><strong>Preference settings</strong>: theme, language, interface state, recently used model;</li>
                <li><strong>Consent and identifiers</strong>: telemetry consent state, anonymous identifier, device identifier, fingerprint reporting throttle mark;</li>
                <li><strong>Session-level temporary information</strong>: the most recently generated API Key (sessionStorage only, automatically cleared when the tab is closed).</li>
            </ul>
            <p>We do not save chat content in local storage. We do not use third-party tracking cookies and do not participate in cross-site advertising tracking. Cloudflare Turnstile may set its own cookies to maintain the verification session, but not for user profiling or advertising. You may disable cookies or clear local storage in browser settings, but disabling them may prevent the login state from being maintained or cause some functions to be unavailable.</p>

            <h2 id="p8">8. Cross-border Data Transfers</h2>
            <p><strong>The Service involves cross-border data transfers, and such transfers are necessary to provide the Service.</strong> The Service relies on global infrastructure such as Cloudflare and Aiven; your data may be stored or processed outside mainland China (such as in Singapore, the United States, Europe, etc.); when you select a model provided by an overseas entity, your input, prompts, files and context will be transferred in real time to a server in the location of that service and processed by that overseas recipient.</p>
            <p>The purpose of transfer is limited to completing the model call and generation service you selected and the necessary technical support; the recipients are the corresponding third-party model service providers and infrastructure service providers such as Cloudflare and Aiven; the processing method is real-time forwarding, temporary processing and storage in accordance with the service provider’s own policy. By reading this Policy and clicking “Agree,” you are deemed to have been fully informed of and to have separately consented to such cross-border data transfer. If you do not agree, please do not use the Service and exercise your deletion right in accordance with Section 10.</p>
            <p>If the volume of personal information we process that is transferred cross-border reaches the threshold for declaration/filing as provided by laws and regulations, we will declare a data-export security assessment to the national cyberspace administration, sign and file a standard contract for cross-border transfer of personal information (SCC), or obtain certification, and continue to satisfy relevant laws and regulations.</p>

            <h2 id="p9">9. Protection of Minors</h2>
            <p>The Service is not directed to children under 14 years of age. If you are under 14, please do not register an account. If you discover that a child under 14 is using the Service, please inform us through the contact information at the end of this Policy; we will delete the relevant account and data after verification. Users aged 14 to 18 are advised to read this Policy with their guardians.</p>

            <h2 id="p10">10. Your Rights</h2>
            <p>You have the following rights regarding your personal information:</p>
            <ul>
                <li><strong>Right of access</strong>: after logging in, view your conversation history through the session list;</li>
                <li><strong>Right of rectification</strong>: if you need to change your email, please apply through the contact information at the end of this Policy; we will process it after identity verification;</li>
                <li><strong>Right of erasure</strong>: you may delete individual sessions; you may also apply to cancel your account, and we will delete or anonymize your data within a reasonable period after verification. However, transaction records, billing records, audit logs and law-enforcement investigation materials that are required to be preserved by laws and regulations will be retained for the statutory minimum period and cannot be deleted immediately;</li>
                <li><strong>Right to copy/portability</strong>: you may apply for a copy of your personal information;</li>
                <li><strong>Right to withdraw consent</strong>: you may turn off the model improvement authorization in Settings at any time, or clear the telemetry consent state;</li>
                <li><strong>Right to complain</strong>: if you believe we have violated this Policy or relevant laws and regulations, you may complain to the Service or to the regulatory authority.</li>
            </ul>
            <p>Exercise of the above rights is usually free of charge; if a request is clearly unfounded, excessively repetitive or requires substantial technical cost, we may refuse to process it or require payment of a reasonable cost fee. The specific cost standard will be communicated when the request is accepted.</p>

            <h2 id="p11">11. Policy Updates</h2>
            <p>We may revise this Policy from time to time. The revised Policy will be published on this page and marked with the “Last updated” date. For changes that affect your material rights and interests, such as an expansion of the scope of collection, the addition of sharing recipients or changes to cross-border arrangements, we will inform you 7 days in advance through site announcements, in-site notices or registered email. By continuing to use the Service after the revised Policy takes effect, you are deemed to accept the revised Policy. If you do not agree to the revision, please stop using the Service and exercise your deletion right in accordance with Section 10.</p>

            <h2 id="p12">12. Operator and Contact Us</h2>
            <p>The Service is provided by an independent operator. We have designated a personal information protection officer. If you need to know the operator information or contact the personal information protection officer, or if you have any questions, suggestions or complaints about this Policy or personal information processing, please contact us through the following methods:</p>
            <ul>
                <li><strong>Official email (including personal information protection officer)</strong>: <a href="mailto:nexusvai@139.com">nexusvai@139.com</a> (please mark “Personal Information Protection Officer”)</li>
                <li><strong>Backup email</strong>: <a href="mailto:nexusvai@foxmail.com">nexusvai@foxmail.com</a></li>
                <li><strong>GitHub Issues</strong>: <a href="https://github.com/NexusVAI" target="_blank" rel="noopener">github.com/NexusVAI</a> (privacy-related requests should be submitted by email)</li>
                <li><strong>X (Twitter)</strong>: <a href="https://x.com/NexusVAI" target="_blank" rel="noopener">@NexusVAI</a></li>
                <li><strong>Website</strong>: <a href="https://www.nexusvai.xyz/" target="_blank" rel="noopener">www.nexusvai.xyz</a></li>
            </ul>
            <p>We will respond within a reasonable period after receiving the request. The Chinese version of this Policy is the authoritative version; if there are other language versions and they conflict with the Chinese version, the Chinese version shall prevail.</p>

            <p class="legal-footer-note">
                <strong>The Chinese version of this Policy is the official version.</strong>
            </p>
      `.trim()
    }
  };

  // Capture the original Chinese content so switching back to Chinese still works.
  function captureZhText(key, el) {
    if (!el) return;
    if (!window.translations.zh) window.translations.zh = {};
    const value = el.textContent.trim();
    if (value) window.translations.zh[key] = value;
    el.setAttribute('data-i18n', key);
  }

  function captureZhHtml(key, el) {
    if (!el) return;
    if (!window.translations.zh) window.translations.zh = {};
    const value = el.innerHTML.trim();
    if (value) window.translations.zh[key] = value;
    el.setAttribute('data-i18n-html', key);
  }

  function captureZhAttr(key, el, attr) {
    if (!el) return;
    if (!window.translations.zh) window.translations.zh = {};
    const value = el.getAttribute(attr) || '';
    if (value) window.translations.zh[key] = value;
    el.setAttribute('data-i18n-content', key);
  }

  const strings = enStrings[prefix];
  if (strings) {
    if (!window.translations.en) window.translations.en = {};
    Object.keys(strings).forEach(function (key) {
      window.translations.en[prefix + '.' + key] = strings[key];
    });
  }

  // Title
  const titleEl = document.querySelector('title');
  if (titleEl) captureZhText(prefix + '.page_title', titleEl);

  // H1 heading
  const h1El = document.querySelector('.legal-title');
  if (h1El) captureZhText(prefix + '.heading', h1El);

  // Category label
  const categoryEl = document.querySelector('.legal-category');
  if (categoryEl) captureZhText(prefix + '.category', categoryEl);

  // Effective date
  const effectiveEl = document.querySelector('.legal-effective');
  if (effectiveEl) captureZhText(prefix + '.effective', effectiveEl);

  // Meta description
  const metaDesc = document.querySelector('meta[name="description"]');
  if (metaDesc) captureZhAttr(prefix + '.meta_description', metaDesc, 'content');

  // OG description (same key as meta description since content is identical)
  const ogDesc = document.querySelector('meta[property="og:description"]');
  if (ogDesc) captureZhAttr(prefix + '.meta_description', ogDesc, 'content');

  // Main legal content
  const contentEl = document.querySelector('.legal-content');
  if (contentEl) captureZhHtml(prefix + '.content', contentEl);
})();
